language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn -DskipTests deploy
  --settings .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn DskipTests clean install";fi
env:
  global:
  - secure: BaisChtfzLY17dwOLar+SrL9E+JRIsBEQrAv611gv4ywHFsavuVrRdszyor87vp/knaWbKok8Q36RLtG2M7OluZZPJdr8iSw8kN3S7SiE02zvviSICE++BlJGQu5ZKLZIl8K5PgmOs0YV0m917AT1PTPd2ZeXDY5BUcOyGr39itUzne00s757ZJlzTJCsvTdte0TDDxD2DMSwwz5Ftuz82If6ZGaHXYXmN6RDxbIQ9aOWW5BExnJpXcOvzdMDJ181jvM+qu0Mu4YlpwdX3Cc9ws1gx2iHC3z97CQVD/GqnsKi2zPV5BkuFlFJWgEg8f8HRxDEe7Z/Ul4I6C7k/PwCxhN8ABPaM+P03IZ+Ba2uihlc2QZnH+O7vLlneA0+O3XJe4LaEqOhNlgmUqkObujMaijmk77M9WKxLwwtZJSEYUoHZhAsL0ixK/YNSRQ8/fRJglUktWtzgBGGSStafa+BUfRxn6HI5Gc4iU77StaOlHGVkaEfEcBKtPjpCXyEqL/ovq648YQTvTquXvpVHJdp1lQqXtS1EDnHlks6S4DOu6g3INwWor4VLGQsv4+rKGHgxrYKGgvPodc+/sFjTBNmcViAm051LMaS0xs9R8/KtWEeLg4Xr/5Azx0zMT0ropsVkTUq0BFVoPgNfkad0TgTxHDdgzZE8I4gXF6F9AFrOI=
  - secure: GqzuzzbWf6j1caVKk2sQxnkVx1YdglB7yNG+Y8vm3mUonEGRhbL+RGfBBQA/rGnNOqGW7d72c+bHgOXTdrOsGUOvkZMs6bPbtzUOtuLPmV5gRjii6BdOYIRIk1mUIOq4vYG4wHsLnmoYjET30xgh7xZ+qHstqJaadDAWPDXdxpPWxTnTQRtjAyDzZgA+yebn0V+Lz0GxYojMxQWdpwXrEc6qa/1xBIHYklzqsIsmGG6eHh/aht7iq2kV7OdTgnX9YApx4ZWbOb4XO8/Q6ZUGqThi28kS/wcP+1kJxaTUxk5C7F/X42AO/APpKgdFC9uNsPKktTd2t20Ew5NLvZAgEGdzAKoxHCkopCUFdSIeRXfmVD//eKPXRYl97IAcG4lZyCQ5Bhw4flNExGYB9B6MyMj4lKHWjkJNU+jzWW2crm7TyvtBR7brafWuvYLkKe/wHu6yc+B/JAFS9BGlTjqqfTWZrzGBA+qYO9FSvhCRJX9IuiOSGmKAavHRGt8Ljm3XRJCu5jtQFgymmJutNh9y3QdPmwFFNQ1eK4EFUTO0oUJ1klUzgY3O5wPFWRE0YPuMnfhBQw+QlphOI1V8RApkl+pk+/yYRHXZm8SvC/Mp8GBNpRe6WF7H36LI7n8UDBlteic++d6Gd5I+85QwzXf3/cw51q2mLmciiXBoN58JyJg=
