language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn -DskipTests deploy
  --settings .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn DskipTests clean install";fi
env:
  global:
  - secure: S6SZ2nM8+m5nP95YuMB0C22EkjKDFD9rp/ScZ+1bvSmyGIcVUw+J2huWuJpIBIeG0esQHeKsRWpYVDiv2ucrtjGCcD3+zOEIJ4wEQsKUJaBfQcb8T4Xf3PPlY27uhWDye7OXCIvk3R/84f+4sHx2wAnefdwoNRqLTW5Xh9IT24v2ariF12JOIYB/D3k4p1MNN7GzVDL3wJ1pNZtYMBYBDreGJdLyrt8T3L8M9BRLxfHUq1h07CGbURkQk5g0Qt9fyJn2qrbU2U/fCDflvQBqqFm8yQBg4OtASImm5H5Hlo4Hn1gI+tZBzwbGLaTw4dGekffWYZ4mU21ka/dIDqXWKjozMhNDlpV6KBLGeLW02U//LcQnLXFYnQUOa6sz0/oTf7ohwWttzQ7rbWGe9j+a+PYLSqZGsQHVHQsd1krybadyGQCNrgg7/JG+O7fTzWPww/nK7q7AQjbYFAbmKfs7Gr+16GqPaMmG4JAWCiEAdnIogIcB9zL3wrYE4/QDzdD7m3dy7eJhs4Z6C2ZN/K5OUwRqXpkIQNbGJkbxwE1I66NBkQCEqusqOF/06luHJCpuvKG+EhfxAmqkyEnVAH3Y9BkP9B0Oc3giCzo/yrz7rFDoJZD+Y1+GE8Bi7hq00p+u/8Aap/Sw8D7ZwWv5+e1B2wmEkxkwi6UdIq3THJ6mwfM=
  - secure: ycMlyW2SXJobQfFU9gigjSnkupAe3G9mDK4jd/iQRydq/lyC9LoYv9xSAZdcm56a6+qD0+jB94yZnzkRcZPtBurGFwyl7uP9gZ1GiDyCqEAf8gw7ssXMMwy8TvpZtK/D2/LaMmo5xkS5mrvbywsp/lyyhDrEk4Fo033p54H+TwZGzkozPqJG3vBz+tpjUkb7+8qeIhq4sovlvGmcObyfIeSQO8v44rPRsmlQYHIhSEdpo6ixCD7cUJK6LAXYf7GdKuMBXACAhbbBLaJ8FvFsSDiyAG55IQAjmmeFWGYkMrSeZuK+Y/+JHGJY/fxnJHU0/jMbfllFynZG+YO9F+DjrTSSyNi63O1J/X4/y+oMgv8BdKWkmskxUAz9F4zAWzodSOlGfUduAqONxEKjN3XW/kuw5iO524SZRtXL79eX5+uVFwsPjDIcGVze4E3Q9HGz7ykI2WZSBCToNm6greILYcHpNIzKQXV664yodAHEVC3mJ21JEZz9CYoTdC/sXqFp0H9MOxc+UU/atbTwMOFhOcGDE/KlfMRip7E9ujgwAN8gh1NKP2yi3chXtU3Eyh7mUar0Kd98kuL0urh5z2P5ceucFlRdaXCI2cMVfXsKHn1f17ry7oR7F0yVvnRb/RwtNLV02w/NkwEUPQXKTUfK8yVC9pf5MTPvP13XMls0OKI=
