language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn -DskipTests deploy
  --settings .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn DskipTests clean install"
  ;fi
env:
  global:
  - secure: G+NpWD8MomdGAMc7TkSzTb92OmtUy08i53cU2H/cyzdvhfTOBJ5sp2vI+bSQ0NHXj7HBCyR6MO5mTQlTrYAaNlHKy6t0MYX4V3nPtQ869rvEerwsVJXrgLUMrE1ci1ghZGhaBF5w4SkjbsPbteU4s1ZIDPAlWbod7rET2PhLdIkf4w/UYfhFTR6O7y15Apfcikzs9i7JNZgoSsoMZT4gWp/rNIbcXz6SNJvA1tUrKHNqqaDwtFo7HRVj+fT5HAgVEPyKDf9iSdpFmPrjogkerZbFJZ8GfRi2s7G4VWQYkGZmBXHPmzb0jpjSk/3J9ZIQnKfQBUHWUztfPC2QA/24a03kSGFaYmCe+KRdBmlmVDilf+GEfUAtJX+eoIRaTKiFSIyWtghOqvNkGrpZGl9MHkurICzgKFJPahedIcXatxsvrBWhR0f9OhRhT8CUmBu8PJ0nImiy2LN623lZCLs43RjZLxR0H5934TBQ9QE9CV1MWuiElcY2ug7/jjJ+euXr/p901olZxHjIWLCuNxiw/Nw+V1o+DI83Vqfx+Pbll6zt3VjThn9SBfsgK6Fi3NvOPQCmdsNEGmJR+vlu/q4nbYS0DRmegTmrJRRCsOir1olEH4aDcetfmjVg796abAJ+Qf+fG14BYiAVRgdrJO8YT7cCtFo6p6c1cKbN1TDaTAQ=
  - secure: D3tnK7XWTsJjcAcln68eRSpQvB98L1qCXvRcKTfe2J77gkzuCIf13EclZ1LWn869Fv5W74UCb95zjMVfdxP+Bbx8M8Gq3JNjGQqUS03LlUmA/iWvexKEShS8iZV3B0rjdjhRYXD5CPKFNCt42+rT/zFbMouIbfZtaGlxInR+OzylFiSWIOZxgmvltGI5eUG79SVPbXHr3dE0K9rYz9jscf8POt8RSD8Nsyxp6wEIgGtG/+u4sIE47Tji3Hk5EGtLS0T8VLhoOy7wtCR9lk85UMAUdNHMQ6b3Nzc33YpaWoCsL96X9vRzSchTC/yzfpsPkcT+bANErUUI1AG2ANOm4nGgXCCdCB50wG9NYYui950SL5SQnfELSQ5FhlvI8tb5l1Rhu/cXV5Hs+J/OopkdIvLMu7EQyHz9DW5Jswd0rYqEsu8g2zlDH7LWJMks6/oUAS9D2qQpuKdgOVqoPYJj+a+ug6HCA+4HJJXAubxs9AWkVOXuj/0gwkHPo/BduSV1dIqUoHLLMIqvnqI1T/h+w+caxaa3FDtaoDBskW2AGmnei9hbextf1kwW6Eb6Z0OYC/T1Tvzw+axL7gOI+5ytoTXe+PgyXjON8vzddO6UfO6OaRwtekG8a00WnrPs+M3irmGbrwE5ovE2vE1ISOURcMpLrNjR4bcqd/z4QzOGKdg=
