version: '3'
services:
  mariadb:
    image: mariadb:10.1.37
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  tomcat:
    image: craftercms/authoring_tomcat
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306      
      - DEPLOYER_HOST=deployer
      - DEPLOYER_PORT=9191
      # Please specify the following env variables in your shell or in CURRENT_DIR/.env
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_REGION
      - AWS_ELASTIC_SEARCH_URL
  deployer:
    image: craftercms/diskless_s3_deployer
    ports:
      - 9191:9191
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
    environment:
      - TOMCAT_HOST=tomcat
      - TOMCAT_HTTP_PORT=8080
      # Please specify the following env variables in your shell or in CURRENT_DIR/.env
      - AWS_ELASTIC_SEARCH_URL
volumes:
  mariadb_data:
    name: diskless_s3_crafter_authoring_data_mariadb
  crafter_data:
    name: diskless_s3_crafter_authoring_data
  crafter_logs:
    name: diskless_s3_crafter_authoring_logs
  crafter_temp:
    name: diskless_s3_crafter_authoring_temp