deployer:
  main:
    targets:
      config:
        folderPath: ${targets.dir}
    deployments:
      folderPath: ${deployments.dir}
      output:
        folderPath: ${logs.dir}
      processedCommits:
        folderPath: ${processedCommits.dir}
    logging:
      folderPath: ${logs.dir}
    management:
      # Deployer management authorization token
      # Please update this per installation and provide this token to the status monitors.
      authorizationToken: ${DEPLOYER_MANAGEMENT_TOKEN}
    security:
      encryption:
        # The key used for encryption of configuration properties
        key: ${CRAFTER_ENCRYPTION_KEY}
        # The salt used for encryption of configuration properties
        salt: ${CRAFTER_ENCRYPTION_SALT}