target:
  localRepoPath: ${deployer.main.deployments.folderPath}/${target.siteName}
  engineUrl: ${env:ENGINE_URL}
  engineManagementToken: ${env:ENGINE_MANAGEMENT_TOKEN}
  search:
    serverUrl: ${env:SEARCH_URL}
    elasticsearch:
      # Single Cluster
      urls:
        - ${env:ES_URL}
      username: ${env:ES_USERNAME}
      password: ${env:ES_PASSWORD}

      # Multiple Clusters
#      readCluster:
#        urls:
#        username:
#        password:
#      writeClusters:
#        - urls:
#          username:
#          password:
#        - urls:
#          username:
#          password:
  notifications:
    mail:
      server:
        host: ${env:MAIL_HOST}
        port: ${env:MAIL_PORT}
