target:
  localRepoPath: ${deployer.main.deployments.folderPath}/${target.siteName}
  engineUrl: ${sys:crafter.engine.url}
  search:
    serverUrl: ${sys:crafter.search.url}
    elasticsearch:
      urls:
        - ${sys:crafter.es.url}
  notifications:
    mail:
      server:
        host: ${sys:mail.host}
        port: ${sys:mail.port}
