target:
  localRepoPath: ${deployer.main.deployments.folderPath}/${target.siteName}
  engineUrl: ${sys:tomcat.url}
  search:
    serverUrl: ${sys:tomcat.url}/crafter-search
    elasticsearch:
      urls:
        - ${sys:es.url}
  notifications:
    mail:
      server:
        host: ${sys:mail.host}
        port: ${sys:mail.port}
