target:
  localRepoPath: ${deployer.main.deployments.folderPath}/${target.siteName}
  engineUrl: ${env:ENGINE_URL}
  engineManagementToken: ${env:ENGINE_MANAGEMENT_TOKEN}
  search:
    serverUrl: ${env:SEARCH_URL}
    elasticsearch:
      urls:
        - ${env:ES_URL}
      username: ${env:ES_USERNAME}
      password: ${env:ES_PASSWORD}
  notifications:
    mail:
      server:
        host: ${env:MAIL_HOST}
        port: ${env:MAIL_PORT}
