target:
  localRepoPath: ${deployer.main.deployments.folderPath}/${target.siteName}
  engineUrl: http://${tomcat.host}:${tomcat.http.port}
  search:
    serverUrl: http://${tomcat.host}:${tomcat.http.port}/crafter-search
    elasticSearch:
      urls: http://${es.host}:${es.port}
  notifications:
    mail:
      server:
        host: ${mail.host}
        port: ${mail.port}
