target:
  localRepoPath: ${deployer.main.deployments.folderPath}/${target.siteName}
  engineUrl: http://${sys:tomcat.host}:${sys:tomcat.http.port}
  search:
    serverUrl: http://${sys:tomcat.host}:${sys:tomcat.http.port}/crafter-search
    elasticsearch:
      urls:
        - http://${sys:es.host}:${sys:es.port}
  notifications:
    mail:
      server:
        host: ${sys:mail.host}
        port: ${sys:mail.port}
