version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    ports:
      - 9202:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xss1024K -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_logs:/usr/share/elasticsearch/logs   
  tomcat:
    image: craftercms/delivery/tomcat
    ports:
      - 9080:9080
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
      - crafter_authoring_crafter_data:/data/authoring
    environment:  
      - DEPLOYER_HOST=deployer
      - DEPLOYER_PORT=9191
      - ES_HOST=elasticsearch
      - ES_PORT=9200
  deployer:
    image: craftercms/deployer
    ports:
      - 9192:9191
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
      - crafter_authoring_crafter_data:/data/authoring
    environment:
      - TOMCAT_HOST=tomcat
      - TOMCAT_HTTP_PORT=9080
      - ES_HOST=elasticsearch
      - ES_PORT=9200
volumes:
  es_data:
  es_logs:
  crafter_data:
  crafter_logs:
  crafter_temp:
  crafter_authoring_crafter_data:
    external: true